lesson 1 done
accountF/webixlayouts pull request #1
Opened 2020-02-26 20:47 UTC by accountF

Navigation menu added, the table shows data and form for editing films, there's only a visual markup in it now, isn't functioning at the moment.

2020-02-26 22:06 UTC, notheheanymore approved these changes

2020-02-27 06:11 UTC, Zwillinge requested changes

2020-02-27 06:11 UTC, Zwillinge commented on index.js
> +                            {view: "list", template: "#title#", select: true, css: "navigation-background", data: [
According to the task, List should not contain a vertical scroll.
Also, Datatable should not have a horizontal scroll.

2020-02-27 06:11 UTC, Zwillinge commented on index.js
> +            {type:"clean", cols:[
such layout with  2 surrounding spacers  will make template shrink on small screens 

![template](https://user-images.githubusercontent.com/2278891/75416990-f451c500-5940-11ea-88a1-b1b789235406.png)

2020-02-27 10:31 UTC, notheheanymore approved these changes

2020-02-27 11:05 UTC, Zwillinge approved these changes

2020-02-27 11:05 UTC, merged